/**
 * ProviderHandoff — cross-provider conversation continuity for the
 * multi-provider runtime arc (PR D).
 *
 * When a turn lands on a (thread, runtime, provider, model_ref) combo
 * with no sidecar row AND the thread has prior assistant messages, the
 * handoff packet bridges the gap: a short summary of the conversation
 * so far + the last N raw exchanges, prepended to the new combo's first
 * turn. Without it, switching from Claude Sonnet to Claude Opus (or to
 * Codex when PR E ships) would have the new combo starting blind even
 * though the user perceives the conversation as continuous.
 *
 * Two summary sources, in order of preference:
 *
 *  1. **memory-tier** — runs `runOneShotQuery` with the configured
 *     memory-tier model (Haiku 4.5 by default — cheap, fast, reliable
 *     for short structured summaries). Pure Claude SDK call; no MCP,
 *     no tools, no session resume.
 *  2. **extractive-fallback** — assembles the summary from the first
 *     sentence of each early user turn and the first sentence of each
 *     late assistant turn. No model call. Used when the memory-tier
 *     model is broken or returns empty (e.g. the user is switching
 *     AWAY from Claude precisely because Claude is broken — the
 *     memory tier defaults to Claude, so a Claude outage would break
 *     the summary cascade unless we have a model-free fallback).
 *
 * The recent-messages portion is identical regardless of source — the
 * last N raw conversation turns, trimmed to fit the token budget.
 *
 * **Skip conditions** — `buildProviderHandoff` returns null when:
 *  - Thread has no prior assistant message (fresh thread, nothing to
 *    hand off).
 *  - `messages` query returns empty (defensive).
 *
 * The caller (`_processQuery`) is responsible for additional skip
 * conditions (pulse turns, resume succeeded, /clear pending) — those
 * are AgentService state, not a property of the conversation.
 *
 * See `shared/multi-provider-runtime-spec-2026-05-16.md` §D5 for the
 * full design and the token-budget rationale.
 */

import type { Thread } from '@resonant/shared';
import { getMessages } from './db.js';
import type { NormalizedMessage } from './runtimes/types.js';

/**
 * Summarizer function injected by the caller. AgentService passes
 * `runOneShotQuery` here at the call site — dependency-injected so
 * this module doesn't import `agent.ts` directly (avoids a circular
 * import: agent.ts → handoff.ts → agent.ts) and so tests can pass a
 * mock summarizer without needing the full SDK plumbing.
 *
 * Contract: returns the summary text (may be empty on failure;
 * empty triggers the extractive fallback inside `generateSummary`).
 * The function is expected to never throw — failures should surface
 * as empty strings.
 */
export type SummarizeFn = (opts: {
  prompt: string;
  model: string;
  systemPrompt: string;
}) => Promise<string>;

/**
 * Token budget for a handoff packet. Defaults match spec D5 — 400
 * tokens of summary + 1600 tokens of recent messages = 2000 total.
 * Rough char→token ratio of 4:1 is used for budgeting (deliberately
 * loose; the goal is bounding cost, not exact token accounting).
 */
export interface HandoffBudget {
  summaryTokens: number;
  recentTokens: number;
  totalCap: number;
}

export const DEFAULT_HANDOFF_BUDGET: HandoffBudget = {
  summaryTokens: 400,
  recentTokens: 1600,
  totalCap: 2000,
};

/** Chars per token, rough — used for budget enforcement only. */
const CHARS_PER_TOKEN = 4;

/** Per-message overhead approximation: role label + separators + JSON quoting. */
const PER_MESSAGE_OVERHEAD_CHARS = 32;

/** Suffix appended to a message whose content was truncated to fit the
 *  recent-message budget. Obvious + searchable so a reader who sees a
 *  weird mid-sentence cutoff knows to look here for the cause. */
const TRUNCATION_SUFFIX = ' [...truncated for handoff budget]';

/**
 * Cross-provider handoff packet. Generated by `buildProviderHandoff`,
 * rendered into a prepended system-context block by
 * `renderProviderHandoffAsPrompt`.
 */
export interface ProviderHandoff {
  handoffVersion: 1;
  /** Destination metadata — what combo this packet was built FOR. */
  toRuntime: string;
  toProvider: string;
  toModelRef: string;
  /** Source metadata — best-guess from the most-recent sidecar row
   *  for the thread, or undefined when no prior session exists
   *  (legacy thread with only `current_session_id`, or a thread that
   *  somehow has messages but no sidecar+legacy state). */
  fromModelRef?: string;
  /** Thread name from the threads table. Renders in the prepended
   *  context block so the new combo knows the thread identity. */
  threadTitle: string;
  /** The actual narrative summary, 2-4 sentences typically. */
  summary: string;
  /** Where the summary came from. `extractive-fallback` indicates the
   *  memory-tier call failed and we used the deterministic
   *  first-sentence extraction instead. */
  summarySource: 'memory-tier' | 'extractive-fallback';
  /** Last N raw exchanges, in chronological order, trimmed to fit
   *  `budget.recentTokens`. May be empty if the budget is exhausted
   *  by the summary alone. */
  recentMessages: NormalizedMessage[];
  /** Effective budget that produced this packet (may differ from
   *  caller's request if the message content was naturally smaller). */
  budget: HandoffBudget;
  /** Sum of summary + rendered messages chars / CHARS_PER_TOKEN.
   *  Diagnostic only — caller can log it to spot budget regressions. */
  totalTokensApprox: number;
}

/**
 * Build a handoff packet for the destination combo. Returns null when
 * the thread has nothing to hand off (no prior assistant messages).
 *
 * **Caller responsibilities** — `_processQuery` should additionally
 * skip the build call when:
 *  - The turn is a pulse (`isPulseOrientation` true).
 *  - A session was resumed (`resumeSessionId` resolved to a value).
 *  - The thread has a `/clear` pending (deliberate fresh start).
 *  - The destination combo matches the most-recent sidecar row (no
 *    actual switch — same model continuing).
 *
 * Doing those checks here would require coupling this module to
 * AgentService state; cleaner to let the caller decide.
 */
export async function buildProviderHandoff(opts: {
  thread: Thread;
  targetRuntime: string;
  targetProvider: string;
  targetModelRef: string;
  memoryTierModel: string;
  /** Caller-provided summarizer. AgentService passes `runOneShotQuery`;
   *  tests can pass a mock. See `SummarizeFn` doc for the contract. */
  summarize: SummarizeFn;
  identityCompanionName: string;
  identityUserName: string;
  fromModelRef?: string;
  budget?: HandoffBudget;
}): Promise<ProviderHandoff | null> {
  const budget = opts.budget ?? DEFAULT_HANDOFF_BUDGET;

  // Read enough recent history that we can pick last-N messages AND
  // generate a summary from a wider window. 30 is roughly 3x typical
  // recentN, which gives the summary context without ballooning the
  // memory-tier prompt.
  const allMessages = getMessages({ threadId: opts.thread.id, limit: 30 });
  const conversational = allMessages.filter(
    (m) => (m.role === 'user' || m.role === 'companion') && m.content_type === 'text',
  );

  // Skip: thread has nothing to hand off. A fresh thread (no messages
  // yet) or a thread with only system messages = no handoff. The
  // first-message orientation in `_processQuery` is enough context for
  // the new combo's opening turn.
  const hasPriorAssistantTurn = conversational.some((m) => m.role === 'companion');
  if (!hasPriorAssistantTurn) return null;

  // Normalize message shape for both the summary call + the
  // recentMessages array. Map 'companion' role → 'assistant' so the
  // shape matches the NormalizedMessage union (which mirrors OpenAI
  // conventions; future non-Claude runtimes will need this anyway).
  const normalized: NormalizedMessage[] = conversational.map((m) => ({
    role: m.role === 'companion' ? 'assistant' : 'user',
    content: m.content,
    createdAt: m.created_at,
  }));

  // Generate the summary — memory-tier first, extractive-fallback on
  // any failure / empty result. The memory-tier call is one-shot and
  // read-only when the caller uses `runOneShotQuery` (plan permission
  // mode, no tools, no session persist) so it cannot mutate state.
  //
  // PR D Codex catch (second pass): summary maxChars must be clamped
  // by totalCap too. Without this, a custom budget where
  // `summaryTokens > totalCap` lets the generated summary exceed the
  // full packet cap before recent-message trimming even runs. The
  // later `totalCap` enforcement loop only trims recentMessages, so
  // an oversized summary would survive intact and break the
  // function's end-to-end cap promise. Clamping pre-generation also
  // means the memory-tier model gets the right ceiling AND the
  // extractive fallback inherits the same cap (both call sites read
  // `opts.maxChars` from the same value).
  const summaryMaxTokens = Math.min(budget.summaryTokens, budget.totalCap);
  const { summary, summarySource } = await generateSummary({
    messages: normalized,
    summarize: opts.summarize,
    memoryTierModel: opts.memoryTierModel,
    companionName: opts.identityCompanionName,
    userName: opts.identityUserName,
    maxChars: summaryMaxTokens * CHARS_PER_TOKEN,
  });

  // Trim the recent-messages list to fit `budget.recentTokens`. Take
  // from the tail (most-recent first), keep adding earlier messages
  // until the char budget is exhausted, then reverse to chronological.
  //
  // PR D Codex catch: if a single recent message is bigger than the
  // entire recent-message budget, we still want to include SOME of it
  // (continuity is more useful than blank), but truncated to fit. Take
  // the message tail (most-recent content is usually most relevant for
  // continuation), append an obvious suffix.
  const recentBudgetChars = budget.recentTokens * CHARS_PER_TOKEN;
  const recentMessages: NormalizedMessage[] = [];
  let recentCharsUsed = 0;
  for (let i = normalized.length - 1; i >= 0; i--) {
    const msg = normalized[i];
    const cost = msg.content.length + PER_MESSAGE_OVERHEAD_CHARS;

    if (recentCharsUsed + cost <= recentBudgetChars) {
      // Fits as-is.
      recentMessages.unshift(msg);
      recentCharsUsed += cost;
      continue;
    }

    // Doesn't fit. If we already have at least one message in the
    // window, stop adding older ones (we have a usable tail).
    if (recentMessages.length > 0) break;

    // Otherwise this is the newest message AND it's bigger than the
    // entire recent budget. Truncate its content to fit, preserve the
    // tail, mark with an obvious suffix. Skip entirely only when the
    // budget can't fit even the overhead + suffix.
    const availableForContent = recentBudgetChars - PER_MESSAGE_OVERHEAD_CHARS - TRUNCATION_SUFFIX.length;
    if (availableForContent > 0) {
      const truncatedContent = msg.content.slice(-availableForContent) + TRUNCATION_SUFFIX;
      recentMessages.unshift({ ...msg, content: truncatedContent });
      recentCharsUsed = truncatedContent.length + PER_MESSAGE_OVERHEAD_CHARS;
    }
    break;
  }

  // PR D Codex catch (second half): enforce `budget.totalCap` end-to-end,
  // not just summaryTokens + recentTokens independently. For custom
  // budgets where summary + recent could individually fit their lanes
  // but together exceed totalCap, we trim recent further (drop oldest
  // first; truncate the sole remaining message if still oversized).
  // Summary is left alone — already bounded by `summaryTokens` and
  // semantically the most-compressed piece of content.
  const totalCapChars = budget.totalCap * CHARS_PER_TOKEN;
  while (
    recentMessages.length > 1 &&
    summary.length + recentCharsUsed > totalCapChars
  ) {
    const dropped = recentMessages.shift()!;
    recentCharsUsed -= dropped.content.length + PER_MESSAGE_OVERHEAD_CHARS;
  }
  if (
    recentMessages.length === 1 &&
    summary.length + recentCharsUsed > totalCapChars
  ) {
    // Single newest message still doesn't fit alongside the summary.
    // Truncate its content to the residual budget. If even the overhead
    // + suffix won't fit, drop the message entirely (defensive — should
    // only hit when summary alone consumes the whole totalCap).
    const newest = recentMessages[0];
    const availableForContent =
      totalCapChars - summary.length - PER_MESSAGE_OVERHEAD_CHARS - TRUNCATION_SUFFIX.length;
    if (availableForContent > 0) {
      const truncatedContent = newest.content.slice(-availableForContent) + TRUNCATION_SUFFIX;
      recentMessages[0] = { ...newest, content: truncatedContent };
      recentCharsUsed = truncatedContent.length + PER_MESSAGE_OVERHEAD_CHARS;
    } else {
      recentMessages.length = 0;
      recentCharsUsed = 0;
    }
  }

  const totalCharsApprox = summary.length + recentCharsUsed;
  const totalTokensApprox = Math.ceil(totalCharsApprox / CHARS_PER_TOKEN);

  return {
    handoffVersion: 1,
    toRuntime: opts.targetRuntime,
    toProvider: opts.targetProvider,
    toModelRef: opts.targetModelRef,
    fromModelRef: opts.fromModelRef,
    threadTitle: opts.thread.name,
    summary,
    summarySource,
    recentMessages,
    budget,
    totalTokensApprox,
  };
}

/**
 * Render a `ProviderHandoff` into the system-context block that gets
 * prepended to the new combo's enriched prompt. Format is plain text
 * (any provider can consume it) with explicit section headers so the
 * model can disambiguate handoff context from the actual user message.
 *
 * The "Do not acknowledge this note" instruction matters: without it,
 * many models begin the response with "Picking up where we left
 * off..." or "Got it, continuing from your last conversation..."
 * which breaks immersion. The model should just continue naturally.
 */
export function renderProviderHandoffAsPrompt(handoff: ProviderHandoff): string {
  const fromHint = handoff.fromModelRef
    ? ` from ${handoff.fromModelRef}`
    : '';

  const messagesBlock = handoff.recentMessages.length === 0
    ? ''
    : '\n\nRecent exchanges:\n' +
      handoff.recentMessages
        .map((m) => `${m.role === 'assistant' ? 'Companion' : 'User'}: ${m.content}`)
        .join('\n\n');

  return [
    `[Conversation context — handoff${fromHint} to ${handoff.toModelRef}]`,
    `Thread: ${handoff.threadTitle}`,
    '',
    `Summary so far: ${handoff.summary}`,
    messagesBlock,
    '',
    'Continue the conversation naturally. Do not acknowledge this context note.',
  ].join('\n');
}

// ---------------------------------------------------------------------------
// Internal: summary generation cascade
// ---------------------------------------------------------------------------

interface SummaryResult {
  summary: string;
  summarySource: 'memory-tier' | 'extractive-fallback';
}

async function generateSummary(opts: {
  messages: NormalizedMessage[];
  summarize: SummarizeFn;
  memoryTierModel: string;
  companionName: string;
  userName: string;
  maxChars: number;
}): Promise<SummaryResult> {
  // Primary path — memory-tier model call. Wrapped in try/catch so any
  // failure (network, auth, model error, empty response) falls through
  // to the extractive path. The cascade is intentional: the user is
  // likely switching providers AT THE MOMENT the memory tier becomes
  // unavailable (e.g. switching off Claude because Claude is broken,
  // but memory tier defaults to Claude). Fallback must work without
  // any model call.
  try {
    const conversationText = opts.messages
      .map((m) => {
        const speaker = m.role === 'assistant' ? opts.companionName : opts.userName;
        // Truncate per-message to keep the summary-prompt size bounded
        // even on threads with very long messages.
        const content = m.content.length > 1500 ? m.content.slice(0, 1500) + '...' : m.content;
        return `${speaker}: ${content}`;
      })
      .join('\n\n');

    const systemPrompt = [
      `You are summarizing a conversation between ${opts.companionName} (AI companion) and ${opts.userName} (human partner).`,
      `Write a single paragraph of 2-4 sentences capturing what they discussed, decisions made, and where the conversation currently stands.`,
      `Be concrete and specific — name the actual topics, not "various subjects". Use third person, present tense.`,
      `Output ONLY the summary paragraph. No preamble, no "Here is the summary", no sign-off.`,
    ].join('\n');

    const prompt = `Conversation to summarize:\n\n---\n${conversationText}\n---\n\nWrite the summary now.`;

    const summary = await opts.summarize({
      prompt,
      model: opts.memoryTierModel,
      systemPrompt,
    });

    const trimmed = summary.trim();
    if (trimmed.length === 0) {
      throw new Error('memory-tier summary returned empty');
    }

    // Truncate to the budget if the model overproduced.
    const bounded = trimmed.length > opts.maxChars
      ? trimmed.slice(0, opts.maxChars - 3) + '...'
      : trimmed;

    return { summary: bounded, summarySource: 'memory-tier' };
  } catch (err) {
    const errMsg = err instanceof Error ? err.message : String(err);
    console.warn(`[Handoff] memory-tier summary failed — falling back to extractive: ${errMsg}`);
    return {
      summary: extractiveSummary(opts.messages, opts.companionName, opts.userName, opts.maxChars),
      summarySource: 'extractive-fallback',
    };
  }
}

/**
 * Model-free summary: first sentence of each of the first 2 user
 * turns + first sentence of each of the last 2 assistant turns,
 * concatenated. Coarse but deterministic — preserves the "what was
 * the user asking about" + "where did the conversation land" beats
 * without needing an LLM call.
 */
function extractiveSummary(
  messages: NormalizedMessage[],
  companionName: string,
  userName: string,
  maxChars: number,
): string {
  const users = messages.filter((m) => m.role === 'user');
  const assistants = messages.filter((m) => m.role === 'assistant');

  const earlyUsers = users.slice(0, 2);
  const lateAssistants = assistants.slice(-2);

  const parts: string[] = [];
  for (const m of earlyUsers) {
    parts.push(`${userName}: ${firstSentence(m.content)}`);
  }
  for (const m of lateAssistants) {
    parts.push(`${companionName}: ${firstSentence(m.content)}`);
  }

  const joined = parts.join(' ');
  if (joined.length <= maxChars) return joined;
  return joined.slice(0, maxChars - 3) + '...';
}

/** First sentence (up to ~120 chars), with reasonable terminator detection. */
function firstSentence(text: string): string {
  const trimmed = text.replace(/^\s+/, '');
  const match = trimmed.match(/^(.+?(?:\.\s|!\s|\?\s|\n))/);
  if (match) {
    const sentence = match[1].trim();
    if (sentence.length <= 120) return sentence;
    return sentence.slice(0, 117) + '...';
  }
  if (trimmed.length <= 120) return trimmed;
  return trimmed.slice(0, 117) + '...';
}
